repos:
  - repo: local
    hooks:
      - &black
        id: black
        name: black
        entry: black
        language: system
        types: [ python ]
        exclude: '^requirements\.txt$'

      - &flake8
        id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]
        exclude: '^requirements\.txt$'

      - &pylint
        id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
        exclude: '^requirements\.txt$'

      - &mypy
        id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [ python ]
        exclude: '^requirements\.txt$'
