version: "3"
services:
  fastapi-app:
    build:
      context: .
      dockerfile: config/fastapi/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./facebook-link-tree:/app/facebook-link-tree
    environment:
      - PYTHONPATH=/app
      - DOCKER_CONTAINER=true
    command: ["uvicorn", "facebookspy.src.server.backend.app:app", "--host", "0.0.0.0", "--port", "8000"]

  react-app:
    build:
      context: .
      dockerfile: config/react/Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./facebook-link-tree:/app/facebook-link-tree
    command: ["nginx", "-g", "daemon off;"]
