site_name: Meta Spy Docs
site_url: https://DEENUU1.github.io/meta-spy/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: black
      accent: black
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black
      accent: black

markdown_extensions:
  - attr_list
  - md_in_html
#
#plugins:
#  - glightbox

copyright: |
  &copy; 2023 <a href="https://github.com/DEENUU1"  target="_blank" rel="noopener">Kacper Włodarczyk</a>